### ISSUE TITLE
'lateinit property hull has not been initialized' error when points are aligned

### ISSUE THREAD

**Issue by Ptit-Biscuit** [ricardomatias/delaunator#2]
Hi,

Nice work but I think you made a small typo line 144...
You should populate nhull array otherwise kotlin does not like it :)

I don't see the point of creating a PR just for 1 character but I wanted you to be aware of this issue.

Again nice project and have a good day!

**Comment by ricardomatias** [comment]
Nicely spotted :+1:  

Fixed in f99ef86
