### ISSUE TITLE
How to use getHalfedges()?

### ISSUE THREAD

**Issue by micycle1** [ricardomatias/delaunator#4]
Is find this kind of vertex indexing very confusing. How do I use `getHalfedges()` to ultimately draw each edge (once) from the triangulation?

Furthermore, how do I find the 3 half edges that make up each triangle?

And is there an easy way to get the triangle that shares a half-edge with a given triangle (or given a half-edge, get the (up-to) two triangles that share it) via this indexing scheme?

**Comment by ricardomatias** [comment]
@micycle1 sorry for the very late reply.. Please check the code [here](https://github.com/openrndr/orx/blob/orx-0.3/orx-triangulation/src/main/kotlin/Delaunay.kt) it has what you're looking for. This port follows the original delaunator, therefore these methods are not included.
